development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://yqzontyahvmwtm:a0398abf4d080c8312910fbdf554224dac17e1a0df53d8c72cab31f3df825cc4@ec2-23-21-238-28.compute-1.amazonaws.com:5432/d8brsmhc0e51mj
  channel_prefix: Digiworld_production
