development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://iwzyfsuorpoiqg:128ed6d081ec6cf6d45560f2db33319c7ab732dbc3fc6fdc7bad18912d228710@ec2-54-204-18-53.compute-1.amazonaws.com:5432/d8ehivoap0ltuc
  channel_prefix: Digiworld_production
