development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://tlvmqgsoetrxcn:99bdf7552ee91bc1f8a2417599ff98e06e836dd7282b3d5191b2577bfae75b76@ec2-54-204-21-226.compute-1.amazonaws.com:5432/dedrpcrkedh65g
  channel_prefix: Digiworld_production
