development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ibyelhyighetrq:911e595d40b019e1d6050ae0a36046aabea237be0d7e367140f18a2b993164c9@ec2-107-22-169-45.compute-1.amazonaws.com:5432/d5sil41umgck0r
  channel_prefix: Digiworld_production
