development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: redis://h:p615f714c2f49948d320d297a62e993f92c992dcc7ef9490db192437864da7e9e@ec2-34-238-130-4.compute-1.amazonaws.com:19149
  channel_prefix: Digiworld_production
