# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3dd566b36d1d85a806b593a06c48fe4ebb63777454e82c754be0b5d8d13b771b63dc16a7ddb58a43131da7a6f1cba12e3730bdff4a40d03accfc2d23ba78bcf8

test:
  secret_key_base: d3e3a59199693aaec4d3fba4cde0b79b9518bb6f6b96791f9bd2d7904f1203e6bd0f8bf35a80d7d4e9aa3caf8a3f26773f7ffaa2b71209e0502f1c25469c7e43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
